<?php 
$categories = array ('Medical Practitioners','Chiropractors','Homeopaths','Psychologists','Social Workers','Marriage Counselors','Dermatologists','Nutritionists and Dietitians','Optometrists','Physical Therapists','Hospital','Fitness','Restaurants','Hotels','Fast Food Outlets','Takeaways','Catering','Fashion retailing','Fashion design','Schools','Universities','Colleges','Tutoring','Banking','Professional Advisory','Wealth Management','Mutual Funds','Insurance','Stock Market','Tax','Audit Consulting','Capital Restructuring','Portfolio Management','ecommerce','Saving','Investing','Retirement planning','Financing','Tax planning','Marketing','Sales','Business management','Online Marketing','Industries','Nutrition','Beauty','Medical','Medical Diagnosis','Psychological','Programming','Data Science','Cloud Computing','Good Morning','Good Evening','Good Afternoon','Good Night','Christmas Wishes','Diwali Whishes','Holi Whishes','Eid Wishes','Online Learning','University','School','College','Football','Cricket');

$categories = array_map('strtolower', $categories);

$festivals = array ('New Year','Makar Sankranti','Republic Day','Mardi Gras','Quebec Winter Carnival','World Cancer Day','Rose Day','Propose Day','Chocolate Day','Teddy Day','Promise Day','Hug Day','Kiss Day','Valentines Day','International Womens Day','International Yoga Festival','No Smoking Day','Holi','Shab-E-Barat','World Forestry Day','World Meteorological Day','World Tuberculosis Day','April Fool Day','Ramadan','Ram Navami','Good Friday','Easter','Earth Day','Songkran','Holy Week in Spain','Jamat Ul Vida','Labour Day','World Laughter Day','Eid ul Fitr','Mothers Day','World Military Day','World No Tobacco Day','World Environment Day','World Blood Donor Day','Fathers Day','Doctors Day','Eid al Adha','World Population Day','Parents Day','Friendship Day','Muharram','Raksha Bandhan','Bon','Independence Day','Ganesh Chaturthi','Teachers Day','Regata Storica','Oktoberfest','Gandhi Jayanti','Hermanus Whale Festival','Dussehra','Indian Air Force Day','Milad Un Nabi','Diwali','Day of the Dead','Halloween','Childrens Day','Christmas Day');
$festivals = array_map('strtolower', $festivals);

$platforms = array('freepik.com','shutterstock.com','stock.adobe.com','instagram.com','facebook.com','pinterest.com','dribbble.com','behance.net','designinspiration.com','pttrns.com','Logoinspirations.co','Collectui.com');
$platforms = array_map('strtolower', $platforms);
?>